[[redirects]]
  from = "/async"
  to = "/blog/engineering"
  status = 301

[[redirects]]
  from = "/async/*"
  to = "/blog/engineering/:splat"
  status = 301

[[redirects]]
  from = "/engineering/*"
  to = "/blog/engineering/:splat"
  status = 301
